baseURL = "http://example.org/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
    # Navbar Menus
    # [[menu.nav]]
    #     name    = "About"
    #     url     = "/about"
    #     weight  = 2
    # [[menu.nav]]
    #     name    = "Service"
    #     url     = "/service"
    #     weight  = 3
    # [[menu.nav]]
    #     name    = "Gallery"
    #     url     = "/gallery"
    #     weight  = 4
    # [[menu.nav]]
    #     name    = "Blog"
    #     url     = "/blog"
    #     weight  = 5
    # [[menu.nav]]
    #     name    = "Contact"
    #     url     = "/contact"
    #     weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    #logo = "images/logo.png"
    #logo_alt = "logo"
    #logo_text = "logo_text"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Hi, my  name is Jen Jensha Sibunga"
        description = "Junior Frontend Developer and a graduate Full Stack Developer at Restart Network Bootcamp in Rotterdam"
        btn     = true
        btnText = "Download Resume"
        btnURL  = "pdfs/jensha-resume.pdf"
        [[params.banner.flipText]]
            title   = "Web Developer"
       

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Hello, You can call me Jen and I'm  originally from the Philippines and currently Front End Developer Intern at Ace&Tate<br/><br/> When I was a child Iâ€™ve always imagined how will I help people around me and that encouraged me to become a Nurse in the Philippines.<br/></br/>One of the turning points in my life is when I decided to leave my country to help my siblings with their studies so they can have a better future.<br/><br/>Along the way I met my boyfriend who is a developer and he introduced me to the world of coding. After a while I came across Restart Network and I thought this program will definitely help me widen my knowledge about coding.Restart Network helped and guided me to learn more about what it means to be a developer. Since then I am passionate and working hard to achieve my ambition to become a developer. What I like most about coding is that it gives me happiness whenever I solve problems and challenges. This gives me a sense of achievement, and that inspires me to learn more everyday.In the future, It would be an honour for me to use my coding skills in a community of passionate people who are focussed on helping others."
        image   = "images/about/hanson.jpg"

    # Call to Action
    [params.cta]
        enable  = false
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Projects"
        subtitle= "Projects I worked on during my bootcamp period"

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Footer section
    [params.footer]
        customized  = false # Set this variable to true if you customized the design.
        copyright_owner = "Themefisher"
        copyright_since = "2018"
        # [[params.footer.social]]
        #     icon = "ion-social-facebook"
        #     link = "https://facebook.com"
        # [[params.footer.social]]
        #     icon = "ion-social-twitter"
        #     link = "https://twitter.com"
        [[params.footer.social]]
            icon = "ion-social-linkedin"
            link = "https://www.linkedin.com/in/jenshasibunga/"
        # [[params.footer.social]]
        #     icon = "ion-social-googleplus"
        #     link = "https://googleplus.com"
        [[params.footer.social]]
            icon = "ion-social-github"
            link = "https://github.com/jenjensha"
    