baseURL = "http://jensibunga.com/"
languageCode = "en-us"
title = "Portfolio"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
    # Navbar Menus
    # [[menu.nav]]
    #     name    = "About"
    #     url     = "/about"
    #     weight  = 2
    # [[menu.nav]]
    #     name    = "Service"
    #     url     = "/service"
    #     weight  = 3
    # [[menu.nav]]
    #     name    = "Gallery"
    #     url     = "/gallery"
    #     weight  = 4
    # [[menu.nav]]
    #     name    = "Blog"
    #     url     = "/blog"
    #     weight  = 5
    # [[menu.nav]]
    #     name    = "Contact"
    #     url     = "/contact"
    #     weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    #logo = "images/logo.png"
    #logo_alt = "logo"
    #logo_text = "logo_text"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Hi, my  name is Jen"
        description = "Junior Frontend Developer and a graduate Full Stack Developer at Restart Network Bootcamp in Rotterdam"
        btn     = true
        btnText = "View Github"
        btnURL  = "https://github.com/jenjensha"
        [[params.banner.flipText]]
            title   = "Web Developer"
       

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "My Story"
        content = "I'm originally from the Philippines, where I grew up wanting to help others and that inspired me to become a Nurse.<br>One of the turning points in my life is when I decided to leave my country so I can help support my family so they can have a better future.<br>Moving here in the Netherlands changed everything. It inspired me to reboot my career and I came across Restart Network. Restart Network triggered my interest in learning how to develop websites as I have been curious in the past about the fast changing world of Technology. In the future, It would be an honour for me to use my coding skills in a community of passionate people who are focussed on helping others."

        image   = "images/about/hanson.jpg"

    # Call to Action
    [params.cta]
        enable  = false
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Projects"
        subtitle= "Projects I worked on during my bootcamp period"

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Footer section
    [params.footer]
        customized  = false # Set this variable to true if you customized the design.
        copyright_owner = "Themefisher"
        copyright_since = "2018"
        # [[params.footer.social]]
        #     icon = "ion-social-facebook"
        #     link = "https://facebook.com"
        # [[params.footer.social]]
        #     icon = "ion-social-twitter"
        #     link = "https://twitter.com"
        [[params.footer.social]]
            icon = "ion-social-linkedin"
            link = "https://www.linkedin.com/in/jenshasibunga/"
        # [[params.footer.social]]
        #     icon = "ion-social-googleplus"
        #     link = "https://googleplus.com"
        [[params.footer.social]]
            icon = "ion-social-github"
            link = "https://github.com/jenjensha"
    